# -*- coding: utf-8 -*-
"""DS_Exp1_Descriptive_Statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IqgIKaXGog5xqFjEQYwwc09AjdfSlg9Q
"""

# Loading the Dataset to df

import pandas as pd

df = pd.read_csv("coin_Bitcoin.csv")
df.head()

df.select_dtypes(include='number').mean().to_frame().T

df.select_dtypes(include='number').median().to_frame().T

df.select_dtypes(include='number').mode().iloc[0].to_frame().T

(df.select_dtypes(include='number').max() -
 df.select_dtypes(include='number').min()).to_frame().T

df.select_dtypes(include='number').var().to_frame().T

df.select_dtypes(include='number').std().to_frame().T

(df.select_dtypes(include='number').quantile(0.75) -
 df.select_dtypes(include='number').quantile(0.25)).to_frame().T

df.select_dtypes(include='number').skew().to_frame().T

df.select_dtypes(include='number').kurtosis().to_frame().T