# -*- coding: utf-8 -*-
"""DS_Exp1_Descriptive_Statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IqgIKaXGog5xqFjEQYwwc09AjdfSlg9Q
"""

# Loading the Dataset to df

import pandas as pd

df = pd.read_csv("coin_Bitcoin.csv")
df.head()

# Measures of Central Tendency

print("Mean Close Price:", df['Close'].mean())
print("Median Close Price:", df['Close'].median())
print("Mode Close Price:", df['Close'].mode()[0])

# Measures of Dispersion (Spread)

print("Range:", df['Close'].max() - df['Close'].min())
print("Variance:", df['Close'].var())
print("Standard Deviation:", df['Close'].std())

Q1 = df['Close'].quantile(0.25)
Q3 = df['Close'].quantile(0.75)
print("Interquartile Range (IQR):", Q3 - Q1)

# Shape of the Distribution
skew = df['Close'].skew()
kurt = df['Close'].kurtosis()

print("Skewness:", skew)
print("Kurtosis:", kurt)

# Interpretation of Skewness
if skew > 0:
    print("Distribution is Positively Skewed (Right Skewed)")
elif skew < 0:
    print("Distribution is Negatively Skewed (Left Skewed)")
else:
    print("Distribution is Symmetric")

# Interpretation of Kurtosis
if kurt > 0:
    print("Distribution is Leptokurtic (Highly Peaked)")
elif kurt < 0:
    print("Distribution is Platykurtic (Flat Distribution)")
else:
    print("Distribution is Mesokurtic (Normal Bell Curve)")